apiVersion: v1
kind: Service
metadata:
  namespace: halyard-service
  name: halyard-web
  labels:
    app: halyard
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: halyard-gui
  selector:
    app: halyard
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  namespace: halyard-service
  name: halyard
  labels:
    app: halyard
spec:
  selector:
    matchLabels:
      app: halyard
  replicas: 1
  template:
    metadata:
      labels:
        app: halyard
    spec:
      containers:
      - name: halyard
        image: gcr.io/spinnaker-marketplace/halyard:stable
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: "/root/.hal"
          name: hal-vol
      volumes:
      - name: hal-vol
        persistentVolumeClaim:
          claimName: "hal-claim"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  namespace: halyard-service
  name: "hal-claim"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1G
